<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlaUI.TestStudio.Automation\FlaUI.TestStudio.Automation.csproj" />
    <ProjectReference Include="..\FlaUI.TestStudio.Core\FlaUI.TestStudio.Core.csproj" />
  </ItemGroup>

</Project>
